### ISSUE TITLE
"Configuring model servers" section broken in docs

### ISSUE THREAD

**Issue by piotrpdev** [opendatahub-io/opendatahub-documentation#35]
## Description

Related/duplicate issue in: https://github.com/opendatahub-io/opendatahub.io/issues/203

https://opendatahub.io/docs/working-on-data-science-projects/#model-serving-on-openshift-data-science_model-serving

https://github.com/opendatahub-io/opendatahub.io/blob/3003ff3a63a4f7983980d9623d0e4153504cff02/docs/working-on-data-science-projects/index.html#L4537-L4547

![image](https://github.com/opendatahub-io/opendatahub.io/assets/99439005/3397f894-db3f-4730-bde4-73b7cf740a06)

**Comment by piotrpdev** [comment]
There seems to be a mismatch in the names:
* `configuring-a-model-server-for-your-data-science-project.adoc`
* `adding-a-model-server-to-your-data-science-project.adoc`

https://github.com/opendatahub-io/opendatahub-documentation/blob/d795436260ab6951dafe97e4eccff50e4f8c08f8/modules/configuring-a-model-server-for-your-data-science-project.adoc?plain=1#L3-L4

https://github.com/opendatahub-io/opendatahub-documentation/blob/d795436260ab6951dafe97e4eccff50e4f8c08f8/assemblies/model-serving.adoc?plain=1#L22

**Comment by MelissaFlinn** [comment]
this issue was fixed with https://github.com/opendatahub-io/opendatahub-documentation/commit/de2caa8a20d65c546f25ce866500eb077d93d80f
