### ISSUE TITLE
Remark that Authorino is a must-have for both Model route and Token authentication

### ISSUE THREAD

**Issue by Feelas** [opendatahub-io/opendatahub-documentation#456]
Based on [KServeModal.tsx](https://github.com/opendatahub-io/odh-dashboard/blob/main/frontend/src/pages/modelServing/screens/projects/kServeModal/ManageKServeModal.tsx#L388) which manages ServingRuntimes, it is clear to see that Authorino is a must have.

The [Deploying models by using the single-model serving platform
](https://github.com/opendatahub-io/opendatahub-documentation/blob/main/modules/adding-a-model-server-for-the-multi-model-serving-platform.adoc#L66) documentation page doesn't make that as an explicit must-have, while it is mandatory and the modal doesn't allow the user to deploy external "Model routes" without it.

Therefore, it would make sense to remark that Authorino is necessary for any External Routes to be configurable on to the cluster.

**Comment by syaseen-rh** [comment]
Added prereq to indicate that authorino is required to enable external model routes and token authentication: https://github.com/opendatahub-io/opendatahub-documentation/pull/521

**Comment by syaseen-rh** [comment]
Added prereq to indicate that authorino is required to enable external model routes and token authentication: https://github.com/opendatahub-io/opendatahub-documentation/pull/521
